package org.subiny92.androidstudyexam;

public enum SampleType {
    ConfiguringScreensWithJava,
    ScrollView,
    Mission01,
    Mission02,
    LayoutInflater,
    PDFView,
    Parcelable,
    Service,
    BroadCastReceiver,
    TouchEvent,
    GestureDetector,
    KeyEvent,
    FocusEvent,
    Orientation,
    Orientation2,
    Toast,
    SeekBar,
    Animation,
    SlideAnimation,
    Fragment,
    FragmentApplications,
    ActionBarAndTab,
    WebView,
    KeyPad,
    Mission03,
    Mission04
}
